minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@k8o/*'
  # Renovate security update: vite-plus@0.1.24
  - vite-plus@0.1.24

blockExoticSubdeps: true
verifyDepsBeforeRun: install
savePrefix: ''

allowBuilds:
  esbuild: false
